

#########
GET http://localhost:8000/users
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcwODQxMzM3OSwiZXhwIjoxNzA4NDE2OTc5fQ.kHLbUZ5PVbRGv4LkKr9If0y3JePjgvSAn08xpGd_dRA
content-type : application/json

######


GET http://localhost:8000/users/7`
content-type : application/json

######



POST http://localhost:8000/newuser
content-type : application/json

 {
     "first_name" : "raviteja",
     "lastname" : "kambam",
     "department_id" : "1",
     "salary" : "13000",
     "password":"1237894238"
 
 }

#########
DELETE http://localhost:8000/deleteuser/16


###########

POST http://localhost:8000/login 
Content-Type: application/json

{
    "userId":"1",
    "password":"Reddysai@123"
}

 

######

POST http://localhost:8000/otpsend
Content-Type: application/json

 {
    "number":"9100894136"
 }

 ##################